sonar.projectKey=eu.mydroot.www:ftk
sonar.projectName=ftk
sonar.projectVersion=1.0.0
sonar.token=sqa_cadcf334bd58ca9c861fcecacba4ff1ff9a9cf3c
sonar.sourceEncoding=UTF-8
sonar.sources=.
// sonar.exclusions=
sonar.scm.disabled=true
sonar.python.version=3.14
sonar.coverage.exclusions=**/*
